Repository tohrxyz/chatgpt-open-ui, pull requests merged in 2023-03, with the labels that each got.

#1 Add gpt-3.5-turbo as model
  react-web/src/api/api.js
Labels: enhancement

#7 Add hide api key switch + form borders
  react-web/src/App.js
Labels: enhancement

#8 Fixed result text being squashed together
  react-web/src/App.js
  react-web/src/api/api.js
Labels: enhancement

#11 🧑‍💻 Add rendered codeblocks (#10)
  react-web/.eslintrc.js
  react-web/package-lock.json
  react-web/package.json
  react-web/src/App.js
  react-web/src/components/Codeblock.js
  react-web/src/parseMarkdown/parseMarkdown.js
  react-web/src/prism/prism.css
  react-web/src/prism/prism.js
Labels: enhancement

#12 Add copy to clipboard button
  react-web/src/components/Codeblock.js
Labels: enhancement

#13 Add copy button to code block
  react-web/src/components/Codeblock.js
Labels: enhancement

#14 Update old babel to a new @babel/eslint-parser
  react-web/.eslintrc.js
  react-web/package-lock.json
  react-web/package.json
Labels: bug-fix

#23 Hotfix to ensure code is highlighted correctly
  react-web/src/api/api.js
  react-web/src/components/Codeblock.js
Labels: bug-fix

#24 Fix default web settings
  react-web/public/chatgpt-open-ui-logo-compressed.jpg
  react-web/public/favicon.ico
  react-web/public/index.html
  react-web/public/logo192.png
  react-web/public/logo512.png
  react-web/public/manifest.json
Labels: enhancement, feature-request

#26 Fix blank site after failed parsing + code highlighting
  react-web/src/api/api.js
  react-web/src/parseMarkdown/parseMarkdown.js
Labels: bug-fix

#27 Save entered API key to local storage + load on start-up
  react-web/public/index.html
  react-web/src/App.js
  react-web/src/api/api.js
Labels: enhancement

#28 Dynamic input field
  react-web/src/App.js
  react-web/src/dynamicInput/dynamicInput.js
Labels: enhancement, feature-request, bug-fix

#30 Rethink and fix of dynamic textarea height
  react-web/src/App.js
  react-web/src/dynamicInput/dynamicInput.js
Labels: enhancement, bug-fix
